import React from "react";
import "./index.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "../components/app-sidebar";

const baseClass = "multi-tenant";

export const metadata = {
  description: "Generated by Next.js",
  title: "Next.js",
};

// eslint-disable-next-line no-restricted-exports
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={baseClass} lang="en">
      <body>
        <SidebarProvider>
          <AppSidebar collapsible="icon" />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
